smpl_body_model: ./data/body_models/smpl

offsets: 
    male: [
        [-0.002174,  0.972724,  0.028584],
        [ 0.058581, -0.082280, -0.017664],
        [ 0.043451, -0.386469,  0.008037],
        [-0.014790, -0.426874, -0.037428],
        [ 0.041054, -0.060286,  0.122042],
        [-0.060310, -0.090513, -0.013543],
        [-0.043257, -0.383688, -0.004843],
        [ 0.019056, -0.420046, -0.034562],
        [-0.034840, -0.062106,  0.130323],
        [ 0.004439,  0.124404, -0.038385],
        [ 0.004488,  0.137956,  0.026820],
        [-0.002265,  0.056032,  0.002855],
        [-0.013390,  0.211635, -0.033468],
        [ 0.010113,  0.088937,  0.050410],
        [ 0.071702,  0.114000, -0.018898],
        [ 0.122921,  0.045205, -0.019046],
        [ 0.255332, -0.015649, -0.022946],
        [ 0.265709,  0.012698, -0.007375],
        [ 0.086691, -0.010636, -0.015594],
        [-0.082954,  0.112472, -0.023707],
        [-0.113228,  0.046853, -0.008472],
        [-0.260127, -0.014369, -0.031269],
        [-0.269108,  0.006794, -0.006027],
        [-0.088754, -0.008652, -0.010107]
    ]
    female: [
        [-0.000876,  0.909315,  0.027821],
        [ 0.071361, -0.089584, -0.008046],
        [ 0.030669, -0.364209, -0.006689],
        [-0.011554, -0.383348, -0.043502],
        [ 0.023338, -0.054645,  0.114370],
        [-0.069012, -0.088960, -0.004796],
        [-0.036152, -0.370650, -0.009185],
        [ 0.014029, -0.383638, -0.041892],
        [-0.022043, -0.046410,  0.117900],
        [-0.002508,  0.103257, -0.022185],
        [ 0.003581,  0.127658, -0.001713],
        [ 0.002027,  0.049072,  0.027867],
        [-0.001963,  0.208243, -0.049765],
        [ 0.003517,  0.062322,  0.050205],
        [ 0.075298,  0.117780, -0.036875],
        [ 0.085317,  0.031739, -0.007293],
        [ 0.251247, -0.011967, -0.027518],
        [ 0.238019,  0.009007,  0.000044],
        [ 0.079668, -0.009683, -0.013206],
        [-0.077033,  0.115606, -0.041811],
        [-0.089203,  0.032785, -0.009802],
        [-0.245990, -0.013152, -0.020162],
        [-0.245177,  0.008622, -0.003532],
        [-0.080400, -0.007248, -0.010419]
    ]

parents: [-1, 0, 1, 2, 3, 0, 5, 6, 7, 0, 9, 10, 11, 12, 11, 14, 15, 16, 17, 11, 19, 20, 21, 22]

joint_names: ['Pelvis', 'L_Hip', 'L_Knee', 'L_Ankle', 'L_Foot', 'R_Hip', 'R_Knee', 'R_Ankle', 'R_Foot', 'Spine1', 'Spine2', 'Spine3', 'Neck', 'Head', 'L_Collar', 'L_Shoulder', 'L_Elbow', 'L_Wrist', 'L_Hand', 'R_Collar', 'R_Shoulder', 'R_Elbow', 'R_Wrist', 'R_Hand']

joints_to_use: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 37]

leaf_joints: [10, 11, 15, 22, 23]

lfoot_index: [7, 10]

rfoot_index: [8, 11]